<?php


namespace Inlead\Controller;


use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use VuFindHarvest\OaiPmh\HarvesterFactory;

class InleadHarvesterCommand extends \VuFindHarvest\OaiPmh\HarvesterCommand
{
    public function __construct($client = null, $harvestRoot = null, HarvesterFactory $factory = null, $silent = false, $name = null)
    {
        parent::__construct($client, $harvestRoot, $factory, $silent, $name);
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        return parent::execute($input, $output); // TODO: Change the autogenerated stub
    }

}
